In [7]:
import numpy as np

In [8]:
print(np.__version__) # 1.20.1

1.20.1


### Numpy를 다룰 때 주의할 점
- .dtype으로 데이터타입을 확인할 수 있다.
- int8, int16, int32, int64 등으로 세분화된다.
- <b> 같은 타입이라도 유형이 다르면 오류가 날 가능성이 크기 때문에 자료 유형은 중간중간 확인해주자 </b>

- np.array() : array 만들기
    - .shape : 자료 구조(행, 열)
    - .dtype : 자료 형태

- np.arange() : python의 range()함수와 유사. 
    - np.arange(a, b, c) : a부터 b - 1까지, 각 간격은 c

- np.zeros(), np.ones() : () 내부에는 shape 가 들어가며 shape 내부는 각각 0과 1로 채워짐

- <b> np.array().reshape() : () 내부에는 바꾸고 싶은 shape가 들어감. shape를 바꾸고 싶을 때 사용 </b>
    - -1을 넣는 경우가 있다 : 나머지 구조가 정해졌을 경우 -1 위치는 자동으로 채워줌

### Numpy 인덱싱, 슬라이싱
- [a:b] : <b> b는 포함하지 않는다. 즉 b-1까지. </b>
- 숫자 없이 [:] 만 쓰는 경우 : 모든 요소를 의미함

In [17]:
np.random.randint(1, 10, # 여기도 마찬가지로 뒤의 값은 포함되지 않는다
                  size = (10, 10)) # 사실 이거 찾아보려고 함 ㅎㅎ! size를 지정해주면 주어진 범위의 array를 생성해준다

array([[7, 6, 3, 5, 5, 8, 4, 2, 9, 4],
       [3, 7, 6, 3, 7, 3, 1, 3, 8, 1],
       [4, 6, 4, 8, 4, 2, 3, 9, 1, 6],
       [6, 8, 4, 4, 5, 1, 9, 5, 6, 7],
       [1, 9, 5, 7, 2, 3, 3, 2, 7, 7],
       [5, 5, 3, 5, 1, 2, 3, 5, 4, 2],
       [2, 9, 2, 3, 2, 4, 5, 3, 9, 9],
       [3, 7, 8, 1, 7, 9, 7, 9, 8, 2],
       [4, 4, 3, 8, 3, 9, 5, 3, 5, 2],
       [7, 6, 6, 2, 3, 2, 6, 4, 6, 9]])

#### numpy의 정렬
<b>1. sort()</b>

In [18]:
# 기본 : 오름차순
np.sort(np.array([174, 165, 180, 182, 168]))

array([165, 168, 174, 180, 182])

In [20]:
# 내림차순
np.sort(np.array([174, 165, 180, 182, 168]))[::-1] # 슬라이싱을 요래 넣어주면 됨
# 관련 파라미터가 있나 찾아봤는데 보이진 않고 대신 kind로 정렬 알고리즘을 지정할 수는 있음

array([182, 180, 174, 168, 165])

<b>2. argsort()</b> 
- 정렬한 결과의 "현재" 인덱스를 반환함

In [22]:
np.argsort(np.array([174, 165, 180, 182, 168]))
# 즉 이 배열의 원래 인덱스는 0 1 2 3 4
# 오름차순으로 정렬하면 165 168 174 180 182
# 이들의 "현재" 인덱스  1   4   0   2   3 

array([1, 4, 0, 2, 3], dtype=int64)

- 너무 조금만 다루고 넘어가는 거 아닌가..?